### ISSUE TITLE
GlfwError

### ISSUE THREAD

**Issue by AngelGamer29JA** [deno-windowing/gluten#2]
GlfwError: 65542 WGL: OpenGL ES requested but WGL_ARB_create_context_es2_profile is unavailable
error: Uncaught (in promise) Error: Failed to create window
      throw new Error("Failed to create window");
            ^
    at new WindowGlfw (https://deno.land/x/dwm@0.3.3/src/platform/glfw/window.ts:674:13)
    at createWindow (https://deno.land/x/dwm@0.3.3/src/platform/mod.ts:43:10)
    at new WebGLCanvas (https://deno.land/x/gluten@0.1.6/src/webgl/canvas.ts:18:19)
    at file:///C:/Users/popit/workspace/deno/canvas_test/main.ts:3:16

**Comment by DjDeveloperr** [comment]
Can you provide more information about the OS?

**Comment by AngelGamer29JA** [comment]
> Can you provide more information about the OS?
![image](https://user-images.githubusercontent.com/26339910/233873606-37739b3f-72d0-4f49-b922-a6d6dddab3cc.png)

**Comment by DjDeveloperr** [comment]
This error just means that the requested context version is not available on your system. What context version are you requesting? Seems like an GL ES context. You should also try updating driver version.

**Comment by AngelGamer29JA** [comment]
I have the latest version of my graphics drivers installed, and I have also tried reinstalling them, but the error with OpenGL ES persists. Interestingly, this error only occurs in my program, as other applications that use OpenGL ES do not give me any errors.

**Comment by AngelGamer29JA** [comment]
I solved the bug, it was simply disabling the gles option when using createWindow.

**Comment by AngelGamer29JA** [comment]
I have encountered the same error and haven't been able to solve it. I have reinstalled the graphics drivers and the entire system, searched various websites for information about this error, but found no solution. I have also considered the possibility of an error in the code structure related to the window hints, although I'm not sure if I could be mistaken.

**Comment by AngelGamer29JA** [comment]
I have encountered the same error and haven't been able to solve it. I have reinstalled the graphics drivers and the entire system, searched various websites for information about this error, but found no solution. I have also considered the possibility of an error in the code structure related to the window hints, although I'm not sure if I could be mistaken.
